# Generated by Django 4.2.4 on 2024-09-28 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Areaname", models.CharField(max_length=100, null=True)),
                ("Description", models.CharField(max_length=300, null=True)),
                ("Creationdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NGO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=300, null=True)),
                ("idpic", models.FileField(null=True, upload_to="")),
                ("aboutme", models.CharField(max_length=300, null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("adminremark", models.CharField(max_length=300, null=True)),
                ("Updationdate", models.DateField(null=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliverypic", models.FileField(null=True, upload_to="")),
                ("Creationdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donation.donor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donationname", models.CharField(max_length=100, null=True)),
                ("donationpic", models.FileField(null=True, upload_to="")),
                ("Collectionloc", models.CharField(max_length=300, null=True)),
                ("Description", models.CharField(max_length=300, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("Donationdate", models.DateTimeField(auto_now_add=True)),
                ("adminremark", models.CharField(max_length=300, null=True)),
                ("NGOremark", models.CharField(max_length=300, null=True)),
                ("Updationdate", models.DateField(null=True)),
                (
                    "Ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donation.ngo"
                    ),
                ),
                (
                    "donationarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation.donationarea",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donation.donor"
                    ),
                ),
            ],
        ),
    ]
