# Generated by Django 4.2.16 on 2024-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation",
            "0005_ngo_userpic_alter_donation_id_alter_donationarea_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(model_name="ngo", old_name="User", new_name="user",),
        migrations.AlterField(
            model_name="ngo",
            name="contact",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
