# Generated by Django 4.2.16 on 2024-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0006_rename_user_ngo_user_alter_ngo_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("clothes", "Clothes"),
                            ("book", "Book"),
                            ("e-waste", "E-waste"),
                            ("money", "Money"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="ngo", old_name="Updationdate", new_name="updationdate",
        ),
        migrations.AddField(
            model_name="ngo",
            name="category",
            field=models.ManyToManyField(related_name="ngos", to="donation.category"),
        ),
    ]
