# Generated by Django 4.2.16 on 2024-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0007_category_rename_updationdate_ngo_updationdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="donation", name="donationarea",),
        migrations.AddField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(default="Pending", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
