# Generated by Django 4.2.4 on 2024-10-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0008_city_alter_ngo_status_ngo_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="donation.city",
            ),
            preserve_default=False,
        ),
    ]
