# Generated by Django 4.2.16 on 2024-10-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation",
            "0008_remove_donation_donationarea_donation_donation_type_and_more",
        ),
        ("donation", "0009_alter_ngo_city"),
    ]

    operations = []
