# Generated by Django 4.2.4 on 2024-10-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0010_merge_20241010_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donation.city",
            ),
        ),
    ]
