# Generated by Django 4.2.4 on 2024-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0011_donor_email_alter_ngo_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
